language: node_js
node_js:
  - "8"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - npm test  
after_script:
  - npm run test:report
  - npm run clean
addons:
  chrome: stable
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3