language: node_js
node_js:
  - "10"
dist: xenial
sudo: required
services:
  - xvfb
install:
  - npm install --global rollup
  - npm ci
script:
  - npm run patch
#  - npm run fetch:firefox
  - npm run symlink:create
  - npm run build
  - npm run test  
after_script:
#  - npm run test:report
  - npm run clean