language: node_js
node_js:
  - "10"
install:
  - npm install --global rollup
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - npm run bootstrap
  - npm run build
  - npm run test  
after_script:
  - npm run test:report
  - npm run clean